version: "3"


volumes:
  wpclient: {}
  wpclient_dbdata: {}

services:

  wp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wpclient
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_DISPLAY', false );
          define( 'WP_DEBUG_LOG', true );
          define('FS_METHOD', 'direct');
          define( 'SCRIPT_DEBUG', true );
    volumes:
      - wpclient:/var/www/html
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wpclient
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - wpclient_dbdata:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
